name: C++ Build & Test

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up C++ compiler
      run: sudo apt-get install -y g++

    - name: Build project
      run: |
        mkdir -p build
        g++ -Wall -Wextra -std=c++17 src/*.cpp -o build/biblioteca

    - name: Run tests (if available)
      run: |
        if [ -d "tests" ]; then
          for testfile in tests/*.cpp; do
            g++ -Wall -Wextra -std=c++17 "$testfile" -o build/test_exec && ./build/test_exec
          done
        else
          echo "No tests directory found, skipping tests."
        fi
